@startuml
interface Subject {
    void request();
}
class Proxy implements Subject{
    private RealSubject realSubject=new RealSubject();
    private void preRequest();
    private void postRequest();

    public void request(){
        preRequest();
        realSubject.request();
        postRequest();}

}
class RealSubject implements Subject{
    public void request();
}
class Main {
    public static void main(String[] args) {
        Proxy proxy = new Proxy();
        proxy.request();}
}
@enduml