@startuml
abstract class Image {
    // 注意一定要是protected,让其子类可见
    protected ImageImp imp;
    public abstract void parseFile(String fileName);
    public void setImageImp(ImageImp imageImp);
}
interface ImageImp {
    void doPaint(Matrix m);
}
class LinuxImpl implements ImageImp {
    public void doPaint(Matrix m);
}
class UnixImpl implements ImageImp {
    public void doPaint(Matrix m);
}
class WindowsImpl implements ImageImp {
    public void doPaint(Matrix m);
}
class BMPImage extends Image {
    public void parseFile(String fileName) {
        Matrix matrix = new Matrix();
        imp.doPaint(matrix);}
}
class GIFImage extends Image {
    public void parseFile(String fileName) {
        Matrix matrix = new Matrix();
        imp.doPaint(matrix);}
}
class PNGImage extends Image {
    public void parseFile(String fileName) {
        Matrix matrix = new Matrix();
        imp.doPaint(matrix);}
}
class MainClass {
    public static void main(String[] args) {
        Image pngImage =new PNGImage();
        pngImage.setImageImp(new WindowsImpl());
        pngImage.parseFile("aaa.bat");

        System.out.println();
        Image jpgImage =new JPGImage();
        jpgImage.setImageImp(new MacImpl());
        jpgImage.parseFile("aaa.bat");
        jpgImage.setImageImp(new WindowsImpl());
        jpgImage.parseFile("aaa.bat");
    }
Image o--ImageImp
@enduml