@startuml
+interface DBFactory {
    Connection createConnection();
    Statement createStatement();
}
+class MysqlFactory implements DBFactory {

}
+class OracleFactory implements DBFactory {

}
 +interface Connection {
    void getConnection();
}
+class MysqlConnection implements Connection {
}
+class OracleConnection implements Connection {
}
+interface Statement {
    void getStatement();
}
+class MysqlStatement implements Statement {
}
+class OracleStatement implements Statement {
}
+class Client {
}
MysqlFactory -->MysqlConnection
MysqlFactory -->MysqlStatement
OracleFactory -->OracleConnection
OracleFactory -->OracleStatement
Client -->DBFactory
Client -->Connection
Client -->Statement
@enduml